version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'jc_db'
    restart: always
    environment:
      - MYSQL_DATABASE:'just_casting'
      - MYSQL_ROOT_PASSWORD:'jcdb'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

